name : deployment

on :

  # push :

  #   branches : ["master"]

  workflow_dispatch:

    inputs :


      region :

        description: "Enter your region name : "

        required: true

        type: string


env :

  bucket : sbms-bucket

  tfstate_file : terraform.tfstate

  region: ${{ github.event.inputs.region }}



jobs :

  job1 :

    runs-on : ubuntu-latest



    steps:

      - uses: actions/checkout@v3

      - name: Terraform hashicorp setup

        uses: hashicorp/setup-terraform@v2

        with:

          terraform_version: 1.1.7



      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

          aws-region: ${{ env.region }}



      - name: terraform init

        run: |
          cd module
          terraform init -reconfigure
      - name: terraform plan

        run: |
          cd module
          terraform plan
      - name: terraform apply

        run: |
          cd module
          terraform apply -auto-approve



  job2 :

    needs : job1


    runs-on : ubuntu-latest



    steps:

      - uses: actions/checkout@v3

      - name: Terraform hashicorp setup

        uses: hashicorp/setup-terraform@v2

        with:

          terraform_version: 1.1.7



      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

          aws-region: ${{ env.region }}


      - name: terraform init

        run: |

          terraform init -reconfigure -backend-config="bucket=${{ env.bucket }}" -backend-config="key=${{ env.tfstate_file}}"
      - name: terraform apply

        run: |

          terraform apply -auto-approve



